### ISSUE TITLE
Reply with Group Number and Class Section

### ISSUE THREAD

**Issue by ProfRojas** [camiashley/group-project#1]

**Comment by ProfRojas** [comment]
Also, just to verify that everyone created a GitHub account can you have all of your teammates post a message on this issue. They can just say hello.

**Comment by camiashley** [comment]
Group #1 
Section 01

**Comment by ctran30** [comment]
hello :D

**Comment by demilabel** [comment]
Hello

**Comment by ProfRojas** [comment]
Please have all of your teammates respond. Otherwise, you will only receive partial credit for the GitHub portion.

**Comment by Hoangle95** [comment]
Hello

**Comment by ProfRojas** [comment]
Thanks!
